name: simple workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup working dir
        run: pwd
      - name: Run a multi-line script
        run: make all
