name: simple workflow

on: 
  push:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: compile all
        run: make all

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact/*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: run script
        run: |
            echo $GH_REPO
            echo $GH_TOKEN

      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

