name: simple workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup working dir
        run: |
          pwd
          ls
      - name: compile all
        run: make all
